image: node:10.15.1

cache:
  paths:
    - node_modules/
  key: "node_modules"
  untracked: true

before_script:
  - npm config set always-auth=false
  - npm config set strict-ssl=false
  - npm install

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
    - ./dist
  script:
    - npm run build-ci

deploy:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master

