image: node:10.15.1

cache:
  paths:
    - node_modules/
  key: "node_modules"
  untracked: true

before_script:
  - npm config set always-auth=false
  - npm config set strict-ssl=false
  - npm install

stages:
  - build

build:
  stage: build
  artifacts:
    paths:
    - ./dist
  script:
    - npm run build-ci



